---
apiVersion: batch/v1
kind: Job
metadata:
  name: slama-yarn-job
  labels:
    app: slama-yarn-job
spec:
  template:
    metadata:
      labels:
        app: slama-yarn-job
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      volumes:
        - name: varlog
          emptyDir: { }
      containers:
      - name: slama-yarn
        image: node2.bdcl:5000/slama:latest
        imagePullPolicy: Always
        cmd: ["yarn-submit"]
        args: ["/examples/spark-ml-pipe-lgb-light.py"]
#        env:
#          - name: CELERY_BROKER_URL
#            value: "amqp://guest:guest@rabbitmq-service:5672"
#          - name: CELERY_RESULT_BACKEND
#            value: "redis://redis:6379/1"
#          - name: FITNESS_CONFIG_PATH
#            value: /app/algorithms_for_tuning/genetic_algorithm/config.yaml
#          - name: AUTOTM_FITNESS_TYPE
#            value: "learned_scorer"
        volumeMounts:
          - name: varlog
            mountPath: /var/log/
#      - name: alglog
#        image: busybox
#        imagePullPolicy: IfNotPresent
#        args: [ /bin/sh, -c, 'sleep 15 && tail -n+1 -f /var/log/repeater.log' ]
#        volumeMounts:
#          - name: varlog
#            mountPath: /var/log
      restartPolicy: Never
  backoffLimit: 0
