---
apiVersion: batch/v1
kind: Job
metadata:
  name: slama-yarn-job
  labels:
    app: slama-yarn-job
spec:
  template:
    metadata:
      labels:
        app: slama-yarn-job
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      volumes:
        - name: varlog
          emptyDir: { }
      containers:
      - name: slama-yarn
        image: node2.bdcl:5000/slama:latest
        imagePullPolicy: Always
        cmd: ["yarn-submit"]
        args: ["/examples-spark/spark-ml-pipe-lgb-light.py"]
        env:
          - name: EXPERIMENT
            value: "84"
          - name: LOG_TO_MLFLOW
            value: "1"
          - name: EXECUTOR_INSTANCES
            value: "1"
          - name: AUTOTM_FITNESS_TYPE
            value: "learned_scorer"
        volumeMounts:
          - name: varlog
            mountPath: /var/log/
      restartPolicy: Never
  backoffLimit: 0
