---
apiVersion: batch/v1
kind: Job
metadata:
  name: slama-yarn-job
  labels:
    app: slama-yarn-job
spec:
  template:
    metadata:
      labels:
        app: slama-yarn-job
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      volumes:
        - name: hadoop-configs
          configMap:
            name: hadoop-configs
      containers:
      - name: slama-yarn
        image: node2.bdcl:5000/slama:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: hadoop-configs
            mountPath: /etc/hadoop
        args: ["/src/examples-spark/stage-level-scheduling.py"]
#        args: ["/src/examples-spark/coalescing-map-reduce.py"]
#        args: ["/src/examples-spark/feature-processing-parallel.py"]
#        args: ["/src/examples-spark/mlalgo-folds-parallel.py"]
#        args: ["/src/examples-spark/env-run.py"]
#        args: ["/src/examples-spark/lgbm-folds-parallel.py"]
#        args: ["/src/examples-spark/feature-processing-only.py"]
#        args: ["/src/examples-spark/lgbm-parallel.py"]
#        args: ["/src/examples-spark/reader-only.py"]
#        args: ["/src/examples-spark/spark-ml-pipe-lgb-light.py"]
#        envFrom:
#          - configMapRef:
#              name: hadoop-env
        env:
          - name: HADOOP_CONF_DIR
            value: /etc/hadoop
          - name: MLFLOW_TRACKING_URI
            value: "http://mlflow-exps:5000"
          - name: EXPERIMENT
            value: "4"
#            value: "37"
          - name: LOG_TO_MLFLOW
            value: "1"
          - name: EXECUTOR_INSTANCES
            value: "1"
          - name: EXECUTOR_CORES
            value: "6"
          - name: DATASET
#            value: "used_cars_dataset_1x"
#            value: "used_cars_dataset_4x"
            value: "lama_test_dataset"
          - name: WAREHOUSE_DIR
            value: "hdfs://node21.bdcl:9000/tmp/slama-spark-warehouse-1x"
          - name: EXP_JOB_PARALLELISM
            value: "1"
          - name: PARALLELISM_MODE
            value: "pref_locs"
      restartPolicy: Never
  backoffLimit: 0
