---
apiVersion: batch/v1
kind: Job
metadata:
  name: slama-yarn-job-2
  labels:
    app: slama-yarn-job-2
spec:
  template:
    metadata:
      labels:
        app: slama-yarn-job-2
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      volumes:
        - name: hadoop-configs
          configMap:
            name: hadoop-configs
#            items:
#              - key: core-site.xml
#                path: core-site.xml
#              - key: yarn-site.xml
#                path: yarn-site.xml
      containers:
      - name: slama-yarn
        image: node2.bdcl:5000/slama:latest
        imagePullPolicy: Always
        args: ["/src/examples-spark/spark-reranking.py"]
#        envFrom:
#          - configMapRef:
#              name: hadoop-env
        env:
          - name: HADOOP_CONF_DIR
            value: /etc/hadoop
          - name: EXPERIMENT
            value: "84"
          - name: LOG_TO_MLFLOW
            value: "1"
          - name: EXECUTOR_INSTANCES
            value: "2"
          - name: DRIVER_MEMORY
            value: "10g"
          - name: EXECUTOR_MEMORY
            value: "90g"
          - name: LOG_FILES_TO_MLFLOW
            value: "1"
          - name: DATASET
            value: "netflix_slim"
          - name: WAREHOUSE_DIR
            value: "hdfs://node21.bdcl:9000/tmp/slama-spark-warehouse-1x"
        volumeMounts:
          - name: hadoop-configs
            mountPath: /etc/hadoop
      restartPolicy: Never
  backoffLimit: 0
