---
apiVersion: batch/v1
kind: Job
metadata:
  name: slama-repeater-job
  labels:
    app: slama-repeater-job
spec:
  template:
    metadata:
      labels:
        app: slama-repeater-job
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      volumes:
        - name: hadoop-configs
          configMap:
            name: hadoop-configs
        - name: data
          persistentVolumeClaim:
            claimName: spark-lama-data
      containers:
      - name: slama-yarn
        image: node2.bdcl:5000/slama:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: hadoop-configs
            mountPath: /etc/hadoop
          - name: data
            mountPath: /opt/spark_data/
        command: ["python3"]
        args:
          - "/src/kube-optuna-repeater/repeater/repeater.py"
#          - "--config=/src/conf/optuna-config.py"
#          - "--config=/src/conf/optuna-config-partial-instances-curves.py"
#          - "--config=/src/conf/scalability-mlalgo-config.py"
          - "--config=/src/conf/scalability-cb-config.py"
          - "--runs-log-dir=/opt/spark_data/repeater-logs"
          - "--parallel=4"
          - "--mlflow-tracking-uri=http://node2.bdcl:8811"
          - "--tag=optuna-run"
        env:
          - name: HADOOP_CONF_DIR
            value: /etc/hadoop
      restartPolicy: Never
  backoffLimit: 0
