# cannot use this image due to an issue with threads creation
# see: https://stackoverflow.com/questions/70087344/python-in-docker-runtimeerror-cant-start-new-thread
# encountered on docker 19.03.8
#FROM jupyter/all-spark-notebook:latest
FROM jupyter/all-spark-notebook:ubuntu-20.04

#RUN pip install mlflow-skinny
