---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-slama-jupyterlab-notebooks-2
spec:
  capacity:
    storage: '100Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/SLAMA/jupyterlab_notebooks_2
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-notebooks-2
spec:
  volumeName: pv-slama-jupyterlab-notebooks-2
  storageClassName: local-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '100Gi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slama-jupyterlab-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slama-jupyterlab-2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 1  # maxUnavailable define how many pods can be unavailable
  template:
    metadata:
      labels:
        app: slama-jupyterlab-2
    spec:
      volumes:
        - name: jupyter-config
          configMap:
            name: jupyter-server-config
            items:
              - key: jupyter_server_config.py
                path: jupyter_server_config.py
        - name: data
          persistentVolumeClaim:
            claimName: spark-lama-data
            readOnly: false
        - name: nfs
          persistentVolumeClaim:
            claimName: mnt-nfs
            readOnly: false
        - name: python-envs
          persistentVolumeClaim:
            claimName: python-envs
            readOnly: true
        - name: jars
          persistentVolumeClaim:
            claimName: jars
            readOnly: true
        - name: jupyterlab-notebooks
          persistentVolumeClaim:
            claimName: jupyterlab-notebooks-2
            readOnly: false
        - name: ephemeral
          emptyDir: { }
      containers:
      - name: jupyter
        image: node2.bdcl:5000/yarn-jupyter-lab:slama-yarn
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Gi"
            cpu: "8"
          limits:
            memory: "30Gi"
            cpu: "8"
        envFrom:
          - configMapRef:
              name: hadoop-env
        ports:
        - containerPort: 8888
        - containerPort: 4040
        - containerPort: 4041
        - containerPort: 4042
        - containerPort: 4043
        volumeMounts:
          - name: data
            mountPath: /opt/spark_data/
          - name: nfs
            mountPath: /mnt/nfs/
          - name: ephemeral
            mountPath: "/tmp"
          - name: python-envs
            mountPath: /home/jovyan/python-envs
          - name: jars
            mountPath: /home/jovyan/jars
          - name: jupyterlab-notebooks
            mountPath: /home/jovyan/notebooks
          - name: jupyter-config
            mountPath: /etc/jupyter/jupyter_server_config.py
            subPath: jupyter_server_config.py
---
apiVersion: v1
kind: Service
metadata:
  name: slama-jupyterlab-2
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 32316
      protocol: TCP
      name: jupyter
    - port: 4040
      nodePort: 32317
      protocol: TCP
      name: spark
    - port: 4041
      nodePort: 32318
      protocol: TCP
      name: spark1
    - port: 4042
      nodePort: 32319
      protocol: TCP
      name: spark2
    - port: 4043
      nodePort: 32320
      protocol: TCP
      name: spark3
  selector:
    app: slama-jupyterlab-2
