---
apiVersion: batch/v1
kind: Job
metadata:
  name: replay-yarn-job
  labels:
    app: replay-yarn-job
spec:
  template:
    metadata:
      labels:
        app: replay-yarn-job
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      volumes:
        - name: hadoop-configs
          configMap:
            name: hadoop-configs
#            items:
#              - key: core-site.xml
#                path: core-site.xml
#              - key: yarn-site.xml
#                path: yarn-site.xml
      containers:
      - name: replay-yarn
        image: node2.bdcl:5000/replay:latest
        imagePullPolicy: Always
        args: ["/src/examples-spark/run_experiment.py"]
#        envFrom:
#          - configMapRef:
#              name: hadoop-env
        env:
          - name: HADOOP_CONF_DIR
            value: /etc/hadoop
          - name: LOG_TO_MLFLOW
            value: "True"
          - name: EXECUTOR_INSTANCES
            value: "8"
          - name: DATASET
#            value: "MovieLens__10m"
#            value: "ml25m"
            value: "MillionSongDataset__1"
          - name: MODEL
            value: "ItemKNN"
          - name: USE_BUCKETING
            value: "False"
        volumeMounts:
          - name: hadoop-configs
            mountPath: /etc/hadoop
      restartPolicy: Never
  backoffLimit: 0
